### PR TITLE
Feature responsive all pages

### PR DESCRIPTION
**Pull request by bleachjade**
- I've fixed all of the pages to be responsive on all devices except the profile page that is because I need to wait for the user information from the signup page that not finish yet.

- Please pull this code and test it on your devices if it works or not.

### CODE REVIEW

**Comment by forfeen** [comment]
In the event detail page, I think the event's picture is very too big (my desktop size 1440 px x 798 px )
Screen Shot 2563-11-11 at 19 32 24

**Comment by forfeen** [comment]
In the user's history page, the attending event label is too close with the line.
Screen Shot 2563-11-11 at 19 36 21

**Comment by bleachjade** [comment]
> In the event detail page, I think the event's picture is very too big (my desktop size 1440 px x 798 px )
> Screen Shot 2563-11-11 at 19 32 24



> In the user's history page, the attending event label is too close with the line.
> Screen Shot 2563-11-11 at 19 36 21

**I fixed it! you can check them again and if there is anything to fix more please let me know.**

**Comment by BenZacs** [comment]
in the profile page when I decrease the size page, the picture is go over all of the page.
image

**Comment by JirawadeeSampusri** [comment]
There is no responsive page on the Login page when I decrease the size screen 

messageImage_1605111837009

messageImage_1605111822180

**Comment by bleachjade** [comment]
> There is no responsive page on the Login page when I decrease the size screen
> 
> messageImage_1605111837009
> 
> messageImage_1605111822180

**Don’t forget to run `git pull origin branch` first before you run the server.**

**Comment by bleachjade** [comment]
> in the profile page when I decrease the size page, the picture is go over all of the page.
> image

**Yes! That’s right because I didn’t modify that page yet as I wrote above in my merge comment section**

**Comment by forfeen** [comment]
messageImage_1605187027990
Below the delete button, It has too much space

**Pull request merged**
